<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonAnSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mon_ans')->delete();

        DB::table('mon_ans')->truncate();

        DB::table('mon_ans')->insert([
            [
                'ten_mon' => "Ghẹ hấp",
                'slug_mon' =>     "ghe-hap",
                'hinh_anh' =>     "https://img-global.cpcdn.com/recipes/18fd8d2499a8c866/1200x630cq70/photo.jpg",
                'gia_ban' =>     500,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    15 ,
            ],
            [
                'ten_mon' => "Ghẹ Sốt Me",
                'slug_mon' =>     "ghe-sot-me",
                'hinh_anh' =>     "https://pastaxi-manager.onepas.vn/content/uploads/articles/minhnguyet/ghe-rang-me/ghe-rang-me-2.jpg",
                'gia_ban' =>     600,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    15 ,
            ],
            [
                'ten_mon' => "Ghẹ Sốt Pho mai",
                'slug_mon' => "ghe-sot-pho-mai",
                'hinh_anh' => "https://i.ytimg.com/vi/H65BsOrxzjE/maxresdefault.jpg",
                'gia_ban' =>     600,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    15 ,
            ],
            [
                'ten_mon' => "Tôm hấp",
                'slug_mon' => "tom-hap",
                'hinh_anh' => "https://amthuc10phut.vn/wp-content/uploads/2023/04/4-13.png",
                'gia_ban' =>     450,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    13 ,
            ],
            [
                'ten_mon' => "Gỏi Tôm",
                'slug_mon' => "goi-tom",
                'hinh_anh' => "https://cdn.tgdd.vn/2020/06/CookProduct/1-1200x676-8.jpg",
                'gia_ban' =>     300,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    13 ,
            ],
            [
                'ten_mon' => "Gỏi Tôm Thái Lan",
                'slug_mon' => "goi-tom-thai-lan",
                'hinh_anh' => "https://www.adcfoods.com/wp-content/uploads/2021/11/cach-lam-tom-sot-thai-an-la-ghien-900x675.jpg",
                'gia_ban' =>     250,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    13 ,
            ],
            [
                'ten_mon' => "Mực Hấp",
                'slug_mon' => "muc-hap",
                'hinh_anh' => "https://daubepgiadinh.vn/wp-content/uploads/2019/01/muc-hap-bia.jpg",
                'gia_ban' =>     250,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    14 ,
            ],
            [
                'ten_mon' => "Mực Nướng",
                'slug_mon' => "muc-nướng",
                'hinh_anh' => "https://cdn.tgdd.vn/Files/2019/03/23/1156454/3-cach-lam-muc-nuong-sa-te-han-quoc-va-chao-thom-ngon-kho-cuong-202110301616257259.jpg",
                'gia_ban' =>     150,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    14 ,
            ],
            [
                'ten_mon' => "Mực Xào",
                'slug_mon' => "muc-xao",
                'hinh_anh' => "https://cdn.tgdd.vn/Files/2021/09/07/1380794/cach-lam-muc-xao-thap-cam-thom-ngon-hap-dan-tai-nha-202109071404339880.jpg",
                'gia_ban' =>     100,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    14 ,
            ],
            [
                'ten_mon' => "Hàu Nướng Mỡ Hành",
                'slug_mon' => "hau-nuong-mo-hanh",
                'hinh_anh' => "https://buffetposeidon.com/storage/app/media/Nau-an/11.2022/181122-hau-nuong-mo-hanh-buffet-poseidon.jpg",
                'gia_ban' =>     170,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    11 ,
            ],
            [
                'ten_mon' => "Hàu Nướng Pho Mai",
                'slug_mon' => "hau-nuong-pho-mai",
                'hinh_anh' => "https://cdn.tgdd.vn/2021/11/CookRecipe/Avatar/hau-nuong-pho-mai-bang-noi-chien-khong-dau-thumbnail.jpg",
                'gia_ban' =>     170,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    11 ,
            ],
            [
                'ten_mon' => "Nghêu Hấp",
                'slug_mon' => "ngheu-hap",
                'hinh_anh' => "https://cdn.tgdd.vn/Files/2020/06/29/1266322/cach-lam-ngao-hap-sa-ot-dam-da-nong-hoi-ca-nha-me-tit-202006291328522826.jpg",
                'gia_ban' =>     160,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    11 ,
            ],
            [
                'ten_mon' => "Nghêu Hấp Thái",
                'slug_mon' => "ngheu-hap-thai",
                'hinh_anh' => "https://alaviet.com/vnt_upload/product/11_2022/116A3090.jpg",
                'gia_ban' =>     150,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    11 ,
            ],
            [
                'ten_mon' => "Chíp Chíp Hấp",
                'slug_mon' => "chip-chip-hap",
                'hinh_anh' => "https://shipdoandemff.com/wp-content/uploads/2017/06/Chip-chip-h%E1%BA%A5p-s%E1%BA%A3-ShipdoandemFF.jpg",
                'gia_ban' =>     125,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    11 ,
            ],
            [
                'ten_mon' => "Chíp Chíp Sốt Thái",
                'slug_mon' => "chip-chip-hap",
                'hinh_anh' => "https://i.ytimg.com/vi/Oxc1TxIbX4Y/maxresdefault.jpg",
                'gia_ban' =>     125,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    11 ,
            ],
            [
                'ten_mon' => "Cá Mú Hấp Xì Dầu",
                'slug_mon' => "ca-mu-hap-xi-dau",
                'hinh_anh' => "https://pastaxi-manager.onepas.vn/content/uploads/articles/nguyendoan/anh-blog/ca-mu-hap-xi-dau/cach-lam-ca-mu-hap-xi-dau-1.jpg",
                'gia_ban' =>     800,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    12 ,
            ],
            [
                'ten_mon' => "Cá Mú Sashimi",
                'slug_mon' => "ca-mu-sashimi",
                'hinh_anh' => "https://ngochuong.vn/upload/image/data/Thanh-Thanh/Menu/IMG8993-197.jpg",
                'gia_ban' =>     900,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    12 ,
            ],
            [
                'ten_mon' => "Cá Mú Sashimi",
                'slug_mon' => "ca-mu-sashimi",
                'hinh_anh' => "https://ngochuong.vn/upload/image/data/Thanh-Thanh/Menu/IMG8993-197.jpg",
                'gia_ban' =>     900,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    12 ,
            ],
            [
                'ten_mon' => "Cá Chình Nướng",
                'slug_mon' => "ca-chinh-nuong",
                'hinh_anh' => "https://www.cet.edu.vn/wp-content/uploads/2019/05/thanh-pham-ca-chinh-nuong-muoi-ot.jpg",
                'gia_ban' =>     900,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    12 ,
            ],
            [
                'ten_mon' => "Pepsi",
                'slug_mon' => "pepsi",
                'hinh_anh' => "https://product.hstatic.net/200000371183/product/thung-24-lon-nuoc-ngot-pepsi-khong-calo-330ml-202008212036376710_3f043ef672af4fb099a71f5b063cd98d_1024x1024.jpg",
                'gia_ban' =>    29,
                'tinh_trang' =>    rand(0,1) ,
                'id_danh_muc' =>    7 ,
            ],
            [
                'ten_mon' => "7up",
                'slug_mon' => "7-up",
                'hinh_anh' => "https://bizweb.dktcdn.net/thumb/grande/100/469/765/products/7up.jpg",
                'gia_ban' =>    20,
                'tinh_trang' => rand(0,1) ,
                'id_danh_muc' =>    7 ,
            ],
            [
                'ten_mon' => "Sting Blue Thái Công",
                'slug_mon' => "sting-blue-thai-cong",
                'hinh_anh' => "https://mir-s3-cdn-cf.behance.net/projects/404/c1607e177874029.Y3JvcCw5ODMsNzY5LDk4Myw0Mjg.jpg",
                'gia_ban' =>   15000,
                'tinh_trang' => rand(0,1) ,
                'id_danh_muc' =>    7 ,
            ],
            [
                'ten_mon' => "Rượu Soju",
                'slug_mon' => "ruou-soju",
                'hinh_anh' => "https://cdn.tgdd.vn/2021/05/CookProduct/1200-1200x676-44.jpg",
                'gia_ban' =>   75,
                'tinh_trang' => rand(0,1) ,
                'id_danh_muc' =>    9 ,
            ],
            [
                'ten_mon' => "Rượu Volka",
                'slug_mon' => "ruou-volka",
                'hinh_anh' => "https://ruouxachtay.com/wp-content/uploads/2022/03/ruou-vodka-ba-lan1.jpg",
                'gia_ban' =>   150000,
                'tinh_trang' => rand(0,1) ,
                'id_danh_muc' =>    9 ,
            ],
            [
                'ten_mon' => "Rượu Ba Kích",
                'slug_mon' => "ruou-ba-kich",
                'hinh_anh' => "https://ruoubakich.com.vn/wp-content/uploads/2020/04/Ruou-ba-kich-Can-2L-Chai-Nam-01-e1586244720949.jpg",
                'gia_ban' =>   1000,
                'tinh_trang' => rand(0,1) ,
                'id_danh_muc' =>    9 ,
            ],
            [
                'ten_mon' => "Huda",
                'slug_mon' => "huda",
                'hinh_anh' => "https://cdn.tgdd.vn/Products/Images/2282/113154/bhx/thung-24-lon-bia-huda-330ml-202309191319361732.jpg",
                'gia_ban' =>   15,
                'tinh_trang' => rand(0,1),
                'id_danh_muc' =>    8,
            ],
            [
                'ten_mon' => "Heniken",
                'slug_mon' => "heniken",
                'hinh_anh' => "https://binhminhcompany.vn/hoanghung/5/images/Bia%20Heneiken%20Silver.jpg",
                'gia_ban' =>   25,
                'tinh_trang' => rand(0,1),
                'id_danh_muc' =>    8,
            ],
            [
                'ten_mon' => "tiger",
                'slug_mon' => "tiger",
                'hinh_anh' => "https://product.hstatic.net/200000356473/product/tiger_lon_1d5aa9935f7b40ad89b0648899e3df48.jpg",
                'gia_ban' =>   25,
                'tinh_trang' => rand(0,1),
                'id_danh_muc' =>    8,
            ],
            [
                'ten_mon' => "Nước Khoáng lavie",
                'slug_mon' => "nuoc-khoang-lavie",
                'hinh_anh' => "https://cdn.tgdd.vn/Products/Images/2563/76401/nuoc-khoang-la-vie-500ml-2.jpg",
                'gia_ban' =>   10,
                'tinh_trang' => rand(0,1),
                'id_danh_muc' =>    10,
            ],
            [
                'ten_mon' => "Cơm Chiên Hải Sản",
                'slug_mon' => "com-chien-hai-san",
                'hinh_anh' => "https://cdn.tgdd.vn/Files/2020/09/25/1293451/cach-lam-com-chien-hai-san-gion-ngon-nhu-nha-hang-202201071045003849.jpg",
                'gia_ban' =>   100,
                'tinh_trang' => rand(0,1),
                'id_danh_muc' =>    4,
            ],
            [
                'ten_mon' => "Cơm Chiên Cá Mặn",
                'slug_mon' => "com-chien-ca-man",
                'hinh_anh' => "https://cdn.tgdd.vn/Files/2021/04/10/1342295/cach-lam-com-chien-ca-man-gion-ngon-chuan-nha-hang-202104101405061079.jpg",
                'gia_ban' =>   100,
                'tinh_trang' => rand(0,1),
                'id_danh_muc' =>    4,
            ],
            [
                'ten_mon' => "Mỳ Xào Bò",
                'slug_mon' => "my-xao-bo",
                'hinh_anh' => "https://cdn.tgdd.vn/Files/2019/10/31/1214045/cach-lam-mi-xao-bo-trong-15-phut-cho-bua-sang-them-chat-luong-202112311517237189.jpg",
                'gia_ban' =>   119,
                'tinh_trang' => rand(0,1),
                'id_danh_muc' =>    5,
            ],
            [
                'ten_mon' => "Mỳ Xào Hải Sản",
                'slug_mon' => "my-xao-hai-san",
                'hinh_anh' => "https://cdn.tgdd.vn/2022/07/CookRecipe/Avatar/mi-xao-hai-san-thumbnail.jpg",
                'gia_ban' =>   119,
                'tinh_trang' => rand(0,1),
                'id_danh_muc' =>    5,
            ],
            [
                'ten_mon' => "Miến Xào Cua Bể",
                'slug_mon' => "mien-xao-cua-be",
                'hinh_anh' => "https://cdn.pastaxi-manager.onepas.vn/content/uploads/articles/huyendt/mienxaocua/6.png",
                'gia_ban' =>   119,
                'tinh_trang' => rand(0,1),
                'id_danh_muc' =>    6,
            ],
        ]);
    }
}
